import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface PDFExportOptions {
    title: string;
    subtitle?: string;
    userName?: string;
    selectedYear: number;
    avgSPS: number;
    avgCycleTime: number;
    avgUptime: number;
    avgNVA: number;
}

export async function exportAnalyticsToPDF(options: PDFExportOptions) {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    let yPosition = 20;

    // Add Schneider Electric Logo (text-based for now)
    pdf.setFillColor(61, 205, 88); // Schneider green
    pdf.rect(15, 10, 12, 12, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text('SE', 21, 18, { align: 'center' });

    // Add Header
    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Schneider Electric', 30, 18);

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 100, 100);
    pdf.text('SET SPS Manufacturing Analytics', 30, 23);

    // Add horizontal line
    pdf.setDrawColor(61, 205, 88);
    pdf.setLineWidth(0.5);
    pdf.line(15, 28, pageWidth - 15, 28);

    yPosition = 35;

    // Report Title
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0, 0, 0);
    pdf.text(options.title, 15, yPosition);
    yPosition += 8;

    if (options.subtitle) {
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(100, 100, 100);
        pdf.text(options.subtitle, 15, yPosition);
        yPosition += 8;
    }

    // Metadata Section
    const currentDate = new Date().toLocaleDateString('tr-TR', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });

    pdf.setFontSize(9);
    pdf.setTextColor(80, 80, 80);
    pdf.text(`Report Generated: ${currentDate}`, 15, yPosition);
    yPosition += 5;
    pdf.text(`Generated By: ${options.userName || 'System User'}`, 15, yPosition);
    yPosition += 5;
    pdf.text(`Analysis Year: ${options.selectedYear}`, 15, yPosition);
    yPosition += 5;
    pdf.text(`System: SET SPS Production Management`, 15, yPosition);
    yPosition += 10;

    // Executive Summary Box
    pdf.setFillColor(245, 245, 245);
    pdf.roundedRect(15, yPosition, pageWidth - 30, 45, 3, 3, 'F');

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0, 0, 0);
    pdf.text('📊 Executive Summary', 20, yPosition + 7);

    yPosition += 12;
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');

    // KPI Grid
    const kpiData = [
        { label: 'Average SPS', value: `${options.avgSPS.toFixed(1)}%`, color: [61, 205, 88] },
        { label: 'Cycle Time', value: `${options.avgCycleTime.toFixed(1)} min`, color: [59, 130, 246] },
        { label: 'Uptime', value: `${options.avgUptime.toFixed(1)}%`, color: [16, 185, 129] },
        { label: 'NVA Time', value: `${options.avgNVA.toFixed(1)} min`, color: [239, 68, 68] }
    ];

    const kpiBoxWidth = (pageWidth - 40) / 4;
    let kpiX = 20;

    kpiData.forEach((kpi, index) => {
        // KPI Box
        pdf.setFillColor(255, 255, 255);
        pdf.roundedRect(kpiX, yPosition, kpiBoxWidth - 3, 25, 2, 2, 'FD');

        // Colored top border
        pdf.setFillColor(kpi.color[0], kpi.color[1], kpi.color[2]);
        pdf.rect(kpiX, yPosition, kpiBoxWidth - 3, 3, 'F');

        // Label
        pdf.setTextColor(100, 100, 100);
        pdf.setFontSize(8);
        pdf.text(kpi.label, kpiX + (kpiBoxWidth - 3) / 2, yPosition + 10, { align: 'center' });

        // Value
        pdf.setTextColor(0, 0, 0);
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.text(kpi.value, kpiX + (kpiBoxWidth - 3) / 2, yPosition + 18, { align: 'center' });

        pdf.setFont('helvetica', 'normal');
        kpiX += kpiBoxWidth;
    });

    yPosition += 33;

    // Instructions for charts
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text('📈 Charts and Detailed Analytics', 15, yPosition);
    yPosition += 6;
    pdf.setFontSize(8);
    pdf.text('The following sections contain visual analytics captured from the dashboard.', 15, yPosition);
    yPosition += 10;

    // Capture charts from the page
    const chartsToCapture = [
        { id: 'trend-sps', title: 'SPS Trend Over Years' },
        { id: 'trend-cycletime', title: 'Cycle Time Trend' },
        { id: 'comparison-chart', title: 'Product Performance Ranking' },
        { id: 'time-breakdown', title: 'Manufacturing Time Breakdown' }
    ];

    for (const chart of chartsToCapture) {
        const element = document.getElementById(chart.id);

        if (element) {
            try {
                const canvas = await html2canvas(element, {
                    scale: 2,
                    logging: false,
                    backgroundColor: '#ffffff'
                });

                const imgData = canvas.toDataURL('image/png');
                const imgWidth = pageWidth - 30;
                const imgHeight = (canvas.height * imgWidth) / canvas.width;

                // Check if we need a new page
                if (yPosition + imgHeight + 15 > pageHeight - 20) {
                    pdf.addPage();
                    yPosition = 20;
                }

                // Chart title
                pdf.setFontSize(11);
                pdf.setFont('helvetica', 'bold');
                pdf.setTextColor(0, 0, 0);
                pdf.text(chart.title, 15, yPosition);
                yPosition += 7;

                // Add chart image
                pdf.addImage(imgData, 'PNG', 15, yPosition, imgWidth, imgHeight);
                yPosition += imgHeight + 10;

            } catch (error) {
                console.error(`Error capturing chart ${chart.id}:`, error);
            }
        }
    }

    // Footer on last page
    const footerY = pageHeight - 15;
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Schneider Electric - SET SPS Production Management System', pageWidth / 2, footerY, { align: 'center' });
    pdf.text(`Confidential - Internal Use Only`, pageWidth / 2, footerY + 4, { align: 'center' });

    // Save PDF
    const fileName = `SE_SPS_Analytics_${options.selectedYear}_${Date.now()}.pdf`;
    pdf.save(fileName);

    return fileName;
}

export function generateQuickPDF(title: string, content: string) {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();

    // Header
    pdf.setFillColor(61, 205, 88);
    pdf.rect(10, 10, 12, 12, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text('SE', 16, 18, { align: 'center' });

    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(16);
    pdf.text('Schneider Electric', 25, 18);

    pdf.setFontSize(12);
    pdf.text(title, 10, 35);

    pdf.setFontSize(10);
    pdf.text(content, 10, 50);

    pdf.save(`SE_${title.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
}
